Repository Xayrulloh/ReminderBot, pull requests merged in 2023-11, with the labels that each got.

#116 chore!: drop support multi-language
  config/database.ts
  cron/cron.ts
  helper/keyboardMapper.ts
  helper/language.ts
  query/inline.ts
  scenes/donate.ts
  scenes/fasting.ts
  scenes/index.ts
  scenes/language.ts
  scenes/location.ts
  scenes/notification.ts
  scenes/search.ts
  scenes/start.ts
  scenes/statistic.ts
  server.ts
  translate/en.json
  translate/ru.json
  translate/uz.json
  types/context.ts
  types/database.ts
Labels: wontfix

#123 Hadith2
  config/storage.ts
  cron/cron.ts
  query/inline.ts
  scenes/hadith.ts
  scenes/location.ts
  scenes/search.ts
  scenes/start.ts
  scenes/statistic.ts
  server.ts
Labels: enhancement

#125 MemorySessionStorage bugFix
  config/storage.ts
Labels: bug

#129 refactor: mongo timeout increased; random hadith taken from single qu…
  config/database.ts
  cron/cron.ts
  query/inline.ts
  scenes/location.ts
  scenes/search.ts
  scenes/start.ts
Labels: enhancement
